language: java
jdk:
  - openjdk8
branches:
  only:
    - develop
deploy:
  provider: heroku
  app: battlechat-dev
  on:
    branch: develop
  api_key:
    secure: tnMa7cgfYDrYdAmpmu7kj3lC3Hdcyk4YBAHHMuVx60vUT5Un1IDoBe0Dhxvfj+/3OGupfI/JHAaXNQ8YZB/GQzJzomwA1oxoHW4+wcJEgVnN/OH9vl6K0Wy8bRs7DAYd2tZCN28DBd32nu7e2AS9K3BFxevtmaJ+5ALgO9avota/Uq9JyuBVmHWQ9JNOH7McIQfwkuwhY6JyANj+9+wnj/PNQdqaM1tsvqdjIdEI7KGx30EM1nbSD3/J4BqumV0UUGgKa/3+j7fw7+NE4iuxHtyiik6/mqKptAmi8nFUwNqNCgLudeRIT5iC2qKcE0EqUSAXGW31WpdLq/LjOHcbkLd6lQrJEiU9JdL3X9H3SCYJ0ERa78zPyLk/6T49Czln+C8f6HaST5j3+D6dxf003lpKVqiQpouIQbRRNUuZ+Qx9ZFpHT+Q7NDUQ2AcqKaqCQafldKUfmLUFNF6ManSloP9RTQCA0brFvNRWomNwkPI8Fzo1vqFAwVyYJ8lrlIB70hjY8H0iqzSNQBdGwlWgm2BJeoUNgT2M77OOXF9FU0Xta6k0mjIFQCU6WqaPVC3A0bRIt/QLTh7L/7xbNRABW6aA4L+WqEe5eoGpkBX/GLlIMyxdOGoL0q/Rpyoeu+h5KhmF9vx3T2rTZqq0kd1lhP6Xn+9WLXGyJK9zECkMglQ=
notifications:
  slack:
    secure: KjFWpZb1uW+X2BEKpR+8zWg3k6cL56yS6MZpOB0tUtumeqaItHipmBayTIUfahFBKEXjIO1x2VsIxJoORi2hmlC2s/b0YwBJD6rpfqDlBhcDOfAPMqh3jT8n5muHi15X69wIbEHejvVcNrtW05z6LjnNqOJOPqyIgu0IeiKDm/jqAT7pXnjCe324WGywbflWZfkaPjTb2pqpcVuDOJVO1mP6pMprn4Z6L/MiHpOsSNtixQErzMgIazXx2mZouUsOFsGoyqhaIasIrqYEpB6cPNYnnd9FpHGs4+Ibo3xKWv5yTd3EKjS4eQtCwprousJJ+0eWFkthu0jx8vF8I5pxMuErBBXy0Nuw/MWS8os01sYQNZ5c5Swo94cmY7tiuTcn1Q/r3AZjD6qZSukQjLt9c5wM7N7YZAnmuVeJNPJjWh6k3uxXAb5vijAYlktEtx2DKwpyAkvQPreMjCzsTmASSRmo0wphxyHuObRgSHB1Amj47l79MEOXk0h5wZZ2F42dggJKnTxGotMkTvoprnVTIsQk+V7Q7Ul69mngFBezhCATb23+4U6MTc2kaSUd7Z9eS1QWB9uvj6ASdrZl9+sP+IaeRmmumR+3vuQpHZ3B+ADwjYq+eVfmKk+YnPG1JlQu7Yol5QbssQ+btR6mnQjMEEQ95NGj/cvXvmN7HnQaG2Q=
